account/urls.py
from django.conf.urls import patterns, url

from account import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
)

imageshare/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'ishare.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ishare/', include('ishare.urls', namespace='ishare')),
    url(r'^account/', include('account.urls', namespace='account')),
)

ishare/urls.py
from django.conf.urls import patterns, url

from ishare import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),

    url(r'^upload/$', views.upload, name='upload'),

    url(r'^albums/$', views.albums, name='albums'),

    url(r'^img/detail/(?P<photo_id>\d+)/$',
        views.photo_detail, name='photo_detail'),
    
    url(r'^img/direct/(?P<photo_id>\d+)/$',
        views.photo_direct, name='photo_direct'),

    url(r'^img/json/recent_comment/(?P<photo_id>\d+)/$',
        views.photo_json_recent_comment, name='photo_json_recent_comment'),

    url(r'^img/json/send_comment/(?P<photo_id>\d+)/$',
        views.photo_json_send_comment, name='photo_json_send_comment'),

    url(r'^img/json/vote/(?P<photo_id>\d+)/$',
        views.photo_json_vote, name='photo_json_vote'),

    url(r'^album/(?P<album_id>\d+)/$',
        views.album_detail, name='album_detail'),
)

ishare/models.py
from django.core.urlresolvers import reverse
from django.templatetags.static import static
from django.db import models

from django.contrib.auth.models import User


class Entity(models.Model):
    COMMENT = 'com'
    ALBUM = 'alb'
    IMAGE = 'img'
    ENTITY_TYPE_CHOICES = (
        (COMMENT, 'Comment'),
        (ALBUM, 'Album'),
        (IMAGE, 'Image')
    )
    entity_type = models.CharField(max_length=3, choices=ENTITY_TYPE_CHOICES)
    create_date = models.DateTimeField(auto_now_add=True)

    creator = models.ForeignKey(User)

    def __str__(self):
        return '%s: %s' % (self. entity_type, self.id)


class Album(models.Model):
    title = models.CharField(max_length=255)
    private = models.BooleanField(default=False)
    last_modified_date = models.DateTimeField(auto_now=True)

    entity = models.OneToOneField(Entity, limit_choices_to={
            'entity_type': Entity.ALBUM
        }, primary_key=True)

    def __str__(self):
        return '%s - %s' % (self.entity.id, self.title)

    def image_number(self):
        return self.image_set.count()

    def thumbnail_url(self):
        if self.image_set.count() > 0:
            first_image = self.image_set.all()[0]
            return reverse('ishare:photo_direct', args=(first_image.pk,))
        else:
            return static('ishare/images/default.png')

class Image(models.Model):
    title = models.CharField(max_length=255)
    last_modified_date = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to='photos')
    views = models.IntegerField(default=0)

    entity = models.OneToOneField(Entity, limit_choices_to={
            'entity_type': Entity.IMAGE
        }, primary_key=True)
    album = models.ForeignKey(Album)

    def __str__(self):
        return '%s - %s' % (self.entity.id, self.title)

    def comment_number(self):
        return self.entity.comments.count()

    def voteup_number(self):
        return self.entity.vote_set.filter(is_vote_up=True).count()

    def votedown_number(self):
        return self.entity.vote_set.filter(is_vote_up=False).count()

    def recent_comments(self):
        return self.entity.comments.all()

    def is_voted(self, user):
        if self.entity.vote_set.filter(creator=user).exists():
            return self.entity.vote_set.filter(creator=user)[0]
        else:
            return None


class Comment(models.Model):
    content = models.TextField()
    last_modified_date = models.DateTimeField(auto_now=True)

    entity = models.OneToOneField(Entity, limit_choices_to={
            'entity_type': Entity.COMMENT
        }, primary_key=True, related_name='+')
    target_entity = models.ForeignKey(Entity, related_name='comments')

    def __str__(self):
        return '%s' % self.pk


class Vote(models.Model):
    is_vote_up = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)

    creator = models.ForeignKey(User)
    target_entity = models.ForeignKey(Entity)

    def __str__(self):
        return '%s' % self.pk

ishare/forms.py
from django import forms

from ishare.models import Image, Entity, Album

class UploadImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['album', 'photo']

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        else:
            self.user = None
        super(UploadImageForm, self).__init__(*args, **kwargs)

    def clean(self):
        if not self.user:
            raise forms.ValidationError('No user at all')

    def save(self, commit=True):
        image = super(UploadImageForm, self).save(commit=False)
        image.title = image.photo.name
        if commit:
            entity = Entity(entity_type=Entity.IMAGE, creator=self.user)
            entity.save()
            image.entity = entity
            image.save()
        return image


class CreateAlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['title']

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        else:
            self.user = None
        super(CreateAlbumForm, self).__init__(*args, **kwargs)

    def clean(self):
        if not self.user:
            raise forms.ValidationError('No user at all')

    def save(self, commit=True):
        album = super(CreateAlbumForm, self).save(commit=False)
        
        if commit:
            entity = Entity(entity_type=Entity.ALBUM, creator=self.user)
            entity.save()
            album.entity = entity
            album.save()
        return album

ishare/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static
from django.core import serializers

import json

from ishare.forms import UploadImageForm, CreateAlbumForm
from ishare.models import Entity, Image, Album, Comment, Vote
from ishare import dao

def index(request):
    recent_images = dao.get_recent_images()
    recent_albums = dao.get_recent_albums()
    context = {
        'recent_images': recent_images,
        'recent_albums': recent_albums
    }
    return render(request, 'ishare/index.html', context)


@login_required
def upload(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('ishare:index'))
    else:
        form = UploadImageForm()
        form.fields['album'].queryset = Album.objects.filter(
            entity__creator=request.user)
    return render(request, 'ishare/upload.html', {'form': form})


@login_required
def albums(request):
    context = {}
    if request.method == 'POST':
        form = CreateAlbumForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('ishare:index'))
    else:
        form = CreateAlbumForm()
        recent_albums = dao.get_user_albums(request.user)
        context['recent_albums'] = recent_albums
    context['form'] = form
    return render(request, 'ishare/albums.html', context)


def photo_direct(request, photo_id):
    image = get_object_or_404(Image, pk=photo_id)
    return HttpResponse(image.photo, content_type='image/jpeg')


def photo_detail(request, photo_id):
    image = get_object_or_404(Image, pk=photo_id)
    image.views += 1
    image.save()
    vote = None
    if request.user.is_authenticated():
        vote = image.is_voted(request.user)
    context = {
        'image': image,
        'is_vote_up': vote.is_vote_up if vote else None
    }
    return render(request, 'ishare/photo_detail.html', context)

def photo_json_recent_comment(request, photo_id):
    image = get_object_or_404(Image, pk=photo_id)
    recent_comments = image.recent_comments()

    data = [dao.comment_to_json(c) for c in recent_comments]
    return HttpResponse(json.dumps(data), content_type="application/json")

def photo_json_send_comment(request, photo_id):
    if request.method == 'GET':
        return HttpResponse('Not support method')

    if not request.user.is_authenticated():
        data = {
            'error': {
                'code': 1,
                'msg': 'You are not logon!'
            }
        }
    else:
        image = get_object_or_404(Image, pk=photo_id)
        message = request.POST.get('message')
        if not message:
            data = {
                'error': {
                    'code': 2,
                    'msg': 'Empty comment'
                }
            }
        else:
            entity = Entity(entity_type=Entity.COMMENT, creator=request.user)
            entity.save()
            comment = Comment(
                content=message,
                entity=entity,
                target_entity=image.entity)
            comment.save()
            data = dao.comment_to_json(comment)
    return HttpResponse(json.dumps(data), content_type="application/json")

def photo_json_vote(request, photo_id):
    if request.method == 'GET':
        return HttpResponse('Not support method')

    if not request.user.is_authenticated():
        data = {
            'error': {
                'code': 1,
                'msg': 'You are not logon!'
            }
        }
    else:
        image = get_object_or_404(Image, pk=photo_id)
        is_vote_up = request.POST.get('is_vote_up') == '1'
        print(request.POST.get('is_vote_up'))
        vote = image.is_voted(request.user)
        if vote:
            if vote.is_vote_up != is_vote_up:
                vote.is_vote_up = is_vote_up
                vote.save()
        else:
            vote = Vote(is_vote_up=is_vote_up, 
                        creator=request.user, 
                        target_entity=image.entity)
            vote.save()
        
        data = {
            'voteUpNumber': image.voteup_number(),
            'voteDownNumber': image.votedown_number(),
        }
    return HttpResponse(json.dumps(data), content_type="application/json")


def album_detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album
    }
    return render(request, 'ishare/album_detail.html', context)

ishare/templates/ishare/album_detail.html
{% extends 'ishare/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">{{ album.title }}</h3>
        
      </div>
      <div class="panel-body">
      {% if album.image_set.all %}
        <ul class="list-inline">
        {% for img in album.image_set.all %}
          <li class="pull-left">
            <div class="img-thumb">
              <a href="{% url 'ishare:photo_detail' img.pk %}">
                <img class="img-rounded" src="{% url 'ishare:photo_direct' img.pk %}" title="{{ img.title }}">
              </a>
              <p class="text-center" style="padding-top: 5px;">
                <span class="glyphicon glyphicon-comment"></span><span> {{ img.comment_number }}</span>
                <span class="glyphicon glyphicon-chevron-up"></span><span> {{ img.voteup_number }}</span>
                <span class="glyphicon glyphicon-chevron-down"></span><span> {{ img.votedown_number }}</span>
              </p>
              
            </div>
          </li>
        {% endfor %}
        </ul>
      {% else %}
        <h4>This album has no image!</h4>
      {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

ishare/templates/ishare/albums.html
{% extends 'ishare/base.html' %}
{% load widget_tweaks %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <!--============CreateAlbumForm============-->
      <form role="form" class="form-horizontal" method="POST" action="{% url 'ishare:albums' %}">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <div class="text-danger">{{ form.non_field_errors }}</div>
          </div>
        </div>
        {% endif %}

        {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
          <div class="col-sm-10">
            {{ field|add_class:"form-control" }}
            <span class="help-block">{{ field.help_text }}</span>
            {% if field.errors %}
            <ul class="text-warning list-unstyled">
              {% for error in field.errors %}
              <li><strong>{{ error|escape }}</strong></li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Create</button>
          </div>
        </div>
      </form><!--/CreateAlbumForm-->

      <!--============Album list============-->
      {% if recent_albums %}
        {% for album in recent_albums %}
          <div class="thumbnail">
            <img src="{{ album.thumbnail_url }}" class="img-rounded" alt="{{ album.title }}">
            <div class="caption">
              <a href="#">{{ album.title }}</a>
              <p class="text-muted">{{ album.image_set.count }} photos</p>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h3>You have no album</h3>
      {% endif %}
    </div>
  </div>

{% endblock %}

ishare/templates/ishare/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Upload your dreams{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'ishare/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="{% static 'ishare/styles.css' %}">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'ishare/js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'ishare/bootstrap/js/bootstrap.min.js' %}"></script>
    {% block headerinclude %}{% endblock %}
  </head>
  <body>
    <div class="container">
      {% include 'ishare/header.html' %}
      {% block content %}{% endblock %}
      {% include 'ishare/footer.html' %}
    </div>
  </body>
</html>

ishare/templates/ishare/header.html
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'ishare:index' %}">iShare</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Last</a></li>
        <li><a href="#">Top</a></li>
        <li><a href="#">Random</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'ishare:albums' %}">Albums</a></li>
        <li><a href="{% url 'ishare:upload' %}"><span class="glyphicon glyphicon-cloud-upload"></span> Upload</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{ user.username }} <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'account:profile' %}">Profile</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'account:logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="{% url 'account:login' %}">Login</a></li>
        <li><a href="{% url 'account:register' %}">Register</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

ishare/templates/ishare/index.html
{% extends 'ishare/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-12">

    <!--Anh gan day-->
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Latest images</h3>
      </div>
      <div class="panel-body">
        <ul class="list-inline">
        {% for img in recent_images %}
          <li class="pull-left">
            <div class="img-thumb">
              <a href="{% url 'ishare:photo_detail' img.pk %}">
                <img class="img-rounded" src="{% url 'ishare:photo_direct' img.pk %}" title="{{ img.title }}">
              </a>
              <p class="text-center" style="padding-top: 5px;">
                <span class="glyphicon glyphicon-comment"></span><span> {{ img.comment_number }}</span>
                <span class="glyphicon glyphicon-chevron-up text-success"></span><span class="text-success"> {{ img.voteup_number }}</span>
                <span class="glyphicon glyphicon-chevron-down text-danger"></span><span class="text-danger"> {{ img.votedown_number }}</span>
              </p>
              
            </div>
          </li>
        {% endfor %}
        </ul>

      </div>
    </div> <!--/Anh gan day-->

    <!--Album gan day-->
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Latest albums</h3>
      </div>
      <div class="panel-body">
        <ul class="list-inline">
        {% for album in recent_albums %}
          <li class="pull-left">
            <div class="img-thumb">
              <a href="{% url 'ishare:album_detail' album.pk %}">
                <img class="img-rounded" src="{{ album.thumbnail_url }}" title="{{ album.title }}">
                <span>{{ album.title }}</span>
                <span class="pull-right">{{ album.image_number }} photos</span>
              </a>
            </div>
          </li>
        {% endfor %}
        </ul>

      </div>
    </div> <!--/Album gan day-->

  </div>
</div>
{% endblock %}

ishare/templates/ishare/photo_detail.html
{% extends 'ishare/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">{{ image.title }}
        {% if user.is_authenticated %}
        <div class="btn-group btn-group-xs pull-right" role="group">
          <button id="voteup-btn" type="button" class="btn btn-success" {% if is_vote_up == True %} disabled="disabled" {% endif %}>
            <span class="glyphicon glyphicon-thumbs-up"></span> <span id="voteup-number">{{ image.voteup_number }}</span>
          </button>
          <button id="votedown-btn" type="button" class="btn btn-danger" {% if is_vote_up == False %} disabled="disabled" {% endif %}>
            <span class="glyphicon glyphicon-thumbs-down"></span> <span id="votedown-number">{{ image.votedown_number }}</span>
          </button>
        </div>
        {% endif %} 
        </h3>
        
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <a href="{% url 'ishare:photo_direct' image.pk %}" target="_blank"><img style="width: 100%" src="{% url 'ishare:photo_direct' image.pk %}"></a>
          </div>
        </div>

      </div>
    </div>
  </div><!--/Image-->

  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Information</h3>
      </div>
      <div class="panel-body">
        <ul class="list-inline">
          <li><span class="glyphicon glyphicon-user"></span> {{ image.entity.creator.username }}</li>
          <li><span class="glyphicon glyphicon-eye-open"></span> {{ image.views }} views</li>
          <li><span class="glyphicon glyphicon-picture"></span> {{ image.album.title }}
          </li>
        </ul>
      </div>
    </div><!--/Information-->

    <ul class="list-group" id="comment-list">
      <li class="list-group-item active">Comments</li>
      {% for comment in image.recent_comments %}
      <li class="list-group-item">
        <b><a href="#">{{ comment.entity.creator.username }}</a>: </b><span>{{ comment.content }}</span>
      </li>
      {% empty %}
      <li class="list-group-item">No comment</li>
      {% endfor %}
    </ul>
    {% if user.is_authenticated %}
    <div id="comment-box">
      <form role="form">
        <div id="menu" class="input-group">
          <textarea style="resize: none;" id="message" rows="2" class="form-control" placeholder="Enter message..." autofocus></textarea>
          <span class="input-group-addon">
            <button id="send-btn" class="btn btn-success" type="button">
              Send
            </button>
          </span>
        </div>
      </form>
    </div>
    {% else %}
    <p>You must <a class="btn btn-primary" role="button" href="{% url 'account:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a> to comment</p>
    {% endif %}<!--/Comment box-->
  </div>
</div>
<hr />
<script type="text/javascript">
  // using jQuery
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) == (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
        // or any other URL that isn't scheme relative or absolute i.e relative.
        !(/^(\/\/|http:|https:).*/.test(url));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
        // Send the token to same-origin, relative URLs only.
        // Send the token only if the method warrants CSRF protection
        // Using the CSRFToken value acquired earlier
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
</script>
<script type="text/javascript">
  if (typeof(String.prototype.trim) === "undefined") {
    String.prototype.trim = function() {
        return String(this).replace(/^\s+|\s+$/g, '');
    };
  }

  function createCommentItem(comment) {
    var user = $('<b>').append($('<a>').attr('href', '/u/' + comment.creator.id).text(comment.creator.name));
    var message = $('<span>').text(': ' + comment.content);
    var item = $('<li>').addClass('list-group-item').append(user).append(message);
    return item;
  }


  var commentList = $('#comment-list');
  var commentBox = $('#comment-box');
  var sendBtn = $('button#send-btn');
  var message = $('textarea#message');

  sendBtn.click(function () {
    var msg = message.val().trim();
    if (msg) {
      $.ajax({
        type: "POST",
        url: "{% url 'ishare:photo_json_send_comment' image.pk %}",
        data: { message: msg },
        success: function (res) {
          console.log(res);
          if (res.hasOwnProperty('error')) {
            alert(res.error.msg);
          } else {
            message.val('');
            commentList.append(createCommentItem(res));
            commentList.animate({ scrollTop: commentList[0].scrollHeight}, 1000);
          }
        }
      });
    }
  });

  // vote section
  var voteUpBtn = $('button#voteup-btn');
  var voteDownBtn = $('button#votedown-btn');
  var voteUpText = $('span#voteup-number');
  var voteDownText = $('span#votedown-number');

  function sendVote(isVoteUp) {
    $.ajax({
      type: "POST",
      url: "{% url 'ishare:photo_json_vote' image.pk %}",
      data: { is_vote_up: isVoteUp ? 1 : 0 },
      success: function (res) {
        console.log(res);
        if (res.hasOwnProperty('error')) {
          alert(res.error.msg);
        } else {
          voteUpText.text(res.voteUpNumber);
          voteDownText.text(res.voteDownNumber);
          if (isVoteUp) {
            voteUpBtn.attr('disabled', 'disabled');
            voteDownBtn.removeAttr('disabled');
          } else {
            voteDownBtn.attr('disabled', 'disabled');
            voteUpBtn.removeAttr('disabled');
          }
        }
      }
    });
  }
  voteUpBtn.click(function () { sendVote(true); });
  voteDownBtn.click(function () { sendVote(false); });

</script>
{% endblock %}

ishare/templates/ishare/upload.html
{% extends 'ishare/base.html' %}
{% load widget_tweaks %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <form role="form" class="form-horizontal" method="POST" action="{% url 'ishare:upload' %}" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <div class="text-danger">{{ form.non_field_errors }}</div>
          </div>
        </div>
        {% endif %}

        {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
          <div class="col-sm-10">
            {{ field|add_class:"form-control" }}
            <span class="help-block">{{ field.help_text }}</span>
            {% if field.errors %}
            <ul class="text-warning list-unstyled">
              {% for error in field.errors %}
              <li><strong>{{ error|escape }}</strong></li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Upload</button>
          </div>
        </div>
      </form><!--/UploadForm-->
    </div>
  </div>

{% endblock %}